name       : gsm
version    : 1.0.17
release    : 1
source     :
    - http://www.quut.com/gsm/gsm-1.0.17.tar.gz : 855a57d1694941ddf3c73cb79b8d0b3891e9c9e7870b4981613b734e1ad07601
license    : MIT
component  : programming.library
libsplit   : no
summary    : GSM lossy speech compression library
description: |
    GSM lossy speech compression library
setup      : |
    %patch -p0 < $pkgfiles/gsm-1.0.17-shared.patch
build      : |
    %make CCFLAGS="-c ${CFLAGS} -fPIC"
install    : |
    install -d -m 00755 $installdir/usr/{bin,include/gsm,share/man/man{1,3}}
    install -d -m 00755 $installdir%libdir%

    %make_install \
        INSTALL_ROOT=$installdir/usr \
        GSM_INSTALL_LIB=$installdir%libdir% \
        GSM_INSTALL_INC=$installdir/usr/include/gsm \
        GSM_INSTALL_MAN=$installdir/usr/share/man/man3 \
        TOAST_INSTALL_MAN=$installdir/usr/share/man/man1

    ln -s gsm/gsm.h $installdir/usr/include
